### ISSUE TITLE
DDS textures export wih wrong file extension

### ISSUE THREAD

**Issue by ghost** [OpenMW/osgexport#1]
http://forum.openmw.org/viewtopic.php?f=2&t=3354&p=37376#p37362

**Comment by zinnschlag** [comment]
Is there a reason why this issue is filed here and not in our tracker?

**Comment by psi29a** [comment]
Are we going to have an additional sub-tracker for osgexport on redmine like we do for the Example-Suite?

I'm OK with either by the way, since this is out of the scope of OpenMW itself.

**Comment by zinnschlag** [comment]
The obvious solution would be to take it upstreams. But I am also okay with adding an exporter project to the tracker. scrawl's call.

**Comment by Lamoot** [comment]
Solved by https://github.com/OpenMW/osgexport/commit/b731019944687cd66dfdedfa027b4761c5c34098
